insta_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from .views import HomePage, CreatePost, EditPost, DeletePost

urlpatterns = [
  path('', HomePage.as_view(), name='home'),
  path('post/', CreatePost.as_view(), name='add_post'),
  path('edit/<pk>/', EditPost.as_view(), name='edit_post'),
  path('delete/<pk>/', DeletePost.as_view(), name='delete_post')
]

posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
  legend = models.TextField()
  photo = models.ImageField(upload_to='images/')

  def __str__(self):
    return self.legend

posts/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
  
  class Meta:
    model = Post
    fields = ['legend', 'photo']
    labels = {
      'legend': ('Legenda'),
      'photo': ('Foto')
    }
    widgets = {
      'legend': forms.TextInput(attrs={'class': 'form-control'})
    }

class EditForm(forms.ModelForm):

  class Meta:
    model = Post
    fields = ['legend']
    labels = {
      'legend': ('Legenda')
    }
    widgets = {
      'legend': forms.TextInput(attrs={'class': 'form-control'})
    }

posts/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Post
from .forms import PostForm, EditForm

class HomePage(ListView):
  model = Post
  template_name = 'index.html'

class CreatePost(CreateView):
  model = Post
  form_class = PostForm
  template_name = 'post.html'
  success_url= reverse_lazy('home')

class EditPost(UpdateView):
  model = Post
  form_class = EditForm
  template_name = 'edit.html'
  success_url = reverse_lazy('home')

class DeletePost(DeleteView):
  model = Post
  template_name = 'delete.html'
  success_url = reverse_lazy('home')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Instapy</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <style>
    .photo-list {
      display: flex;
      flex-direction: column;
      justify-content: center;
    }

    .section-container {
      padding: 1rem;
    }

    .card-img-top {
      object-fit: cover;
      width: inherit;
      height: 500px;
    }

    .card-text.icons {
      display: flex;
      justify-content: flex-end;
    }

    .icon-set {
      margin-left: 15px;
    }

    .no-padding {
      padding: 0
    }

    .button-set {
      display: flex;
      justify-content: flex-end;
    }
  </style>

</head>

<body>

  <div class="container">
    <header>
      <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="/">InstaPy</a>
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <a class="nav-link active" href="/post" title="Adicionar nova foto"><i class="fas fa-plus"></i></a>
          </li>         
        </ul>
      </nav>
    </header>
    <section class="section-container">
        {% block content %}
        {% endblock %}
    </section>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="row photo-list">
    <div class="col-6 offset-md-3">
    <form method="post">
      {% csrf_token %}
      <p>Tem certeza que deseja deletar "{{ object }}"?</p>
      <div class="button-set">
        <a class="btn btn-link" value="Confirm" href="/">Cancelar</a>
        <input type="submit" class="btn btn-danger" value="Excluir">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block content %}
<div class="row photo-list">
  <div class="col-6 offset-md-3 edit-set">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="col-12 no-padding">
        <small class="card mb-3">
          <img src="{{object.photo.url}}" class="card-img-top" alt="{{object}}">
        </small>
      </div>
      <div class="button-set">
        <a class="btn btn-link" value="Confirm" href="/">Cancelar</a>
        <input type="submit" class="btn btn-primary" value="Editar">
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="row photo-list">
    <div class="col-6 offset-md-3">
      {% for post in object_list %}
      <div class="col-12">
        <div class="card mb-3">
          <img src="{{post.photo.url}}" class="card-img-top" alt="{{post.legend}}">
          <div class="card-body">
            <p class="card-text">{{post.legend}}</p>
            <p class="card-text icons">
              <a href="/edit/{{post.pk}}" class="icon-set">
                <small class="text-muted">
                  <i class="fas fa-edit"></i>
                </small>
              </a>
              <a href="/delete/{{post.pk}}" class="icon-set">
                <small class="text-muted">
                  <i class="fas fa-trash-alt"></i>
                </small>
              </a>
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
    <div class="col-6">
      <h1 class="text-center">Nova Foto</h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>
    </div>
    <div class="col-6">
      <small class="card mb-3">
        <img src="{{form.photo.url}}" id="preview" class="card-img-top" alt="{{object}}">
      </small>  
    </div>
  </div>

  <script>
  const file = document.querySelector('#id_photo');
  file.addEventListener('change', function(e) {
    var reader = new FileReader();
    const preview = document.querySelector('#preview');
    reader.onload = e => {
      preview.setAttribute('src', e.target.result)
    }
    reader.readAsDataURL(this.files[0])
  })
  </script>
{% endblock %}